//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepKomputerowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametryDict
    {
        public int IdProduktu { get; set; }
        public int Id { get; set; }
        public string Parametr { get; set; }
        public string Wartosc { get; set; }
    
        public virtual Produkty Produkty { get; set; }
    }
}
