//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklepKomputerowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Kod { get; set; }
        public decimal Cena { get; set; }
        public string AdresObrazka { get; set; }
        public string Opis { get; set; }
    }
}
